name: diffusion-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=0.13.0
  - pytorch-cuda=11.8
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.6.0
  - scikit-learn>=1.0.0
  - tqdm>=4.64.0
  - pip:
    - monai>=1.3.0
    - "monai-weekly[pillow, tqdm]"
    - monai-generative>=0.2.0
    - "diffusers[torch]>=0.21.0"
    - Pillow>=9.0.0
    - tensorboard>=2.10.0
    - wandb>=0.13.0
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - pytest>=6.0
    - black>=22.0
    - flake8>=4.0
    - isort>=5.0
    - mypy>=0.900
    - pandas>=1.5.0
    - seaborn>=0.11.0